spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${SPRING_DATASOURCE_USERNAME:system}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
#  flyway:
#    locations: classpath:db/migration-oracle
#    baseline-on-migrate: true
#    baseline-version: 0